# Generated by Django 2.2.7 on 2019-12-01 10:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20191201_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Starts at : '),
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
